# Site settings
title: The Ambusher Sound
tag_text: The Ambusher Sound
description: Ambient
url: "http://ambushersound.com"
baseurl: ""

font-awesome-include: false # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
